@port = 9000
@api_url = http://localhost:{{port}}

POST {{api_url}}/auth/register
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "j.doe@sample.com",
  "password": "johnDoePass01"
}
