@api_HostAddress = http://localhost:5123

# Jobs
GET {{api_HostAddress}}/api/jobs
###

# Job By ID
GET {{api_HostAddress}}/api/jobs/7073c80c-d2d4-4d68-8b1f-26a95d77d132
###

# Delete Job
DELETE  {{api_HostAddress}}/api/jobs/e533b09f-0000-429f-8c59-848fe33e0e8b
###

# Create a Job
POST  {{api_HostAddress}}/api/jobs
Content-Type: application/json

{
  "title": "Junior Software Engineer 1",
  "description": "Test description",
  "shortDescription": "Test short description",
  "companyName": "Tesla",
  "salary": 75000,
  "currencyCode": "USD",
  "userId": null,
  "anonymousUserName": "Abiel Rodriguez",
  "jobCategoryId": "82dc0028-2e9c-490d-bf4d-94ac83a91685",
  "skills": ["javascript", "html"],
  "salaryType": "Year",
  "jobUserType": "AnonymousUser"
}
###

# Update a Job
PUT  {{api_HostAddress}}/api/jobs/f763ecb6-4d1d-4ac1-bab0-ba33b785041a
Content-Type: application/json

{
  "title": "Senior Accountant 3",
  "description": "Test description",
  "shortDescription": "Test short description",
  "companyName": "Tesla",
  "salary": 75000,
  "currencyCode": "USD",
  "userId": null,
  "anonymousUserName": "Abiel Rodriguez",
  "jobCategoryId": "82dc0028-2e9c-490d-bf4d-94ac83a91685",
  "skills": ["javascript", "seo", "Ef Core"],
  "salaryType": "Year",
  "jobUserType": "AnonymousUser"
}
###
