@api_HostAddress = http://localhost:5123

# Skills
GET {{api_HostAddress}}/api/skills
###

# Skill By ID
GET {{api_HostAddress}}/api/skills/d0c91c72-8193-4cfd-b9be-d4068c65baed
###

# Delete Skill
DELETE  {{api_HostAddress}}/api/skills/d0c91c72-8193-4cfd-b9be-d4068c65baed
###

# Create a Skill
POST  {{api_HostAddress}}/api/skills
Content-Type: application/json

{
 "name": "Css"
}
###

# Update a SKill
PUT  {{api_HostAddress}}/api/skills/d0c91c72-8193-4cfd-b9be-d4068c65baed
Content-Type: application/json

{
  "name": "Javascript"
}
###
