@api_HostAddress = http://localhost:5123

# Skills
GET {{api_HostAddress}}/api/skills
###

# Skill By ID
GET {{api_HostAddress}}/api/skills/0d9091bd-6ec9-4efa-b261-f378912ad440
###

# Create a Skill
POST  {{api_HostAddress}}/api/skills
Content-Type: application/json

{
 "name": "Bootstrap"
}
###
